version: "3.1"

services:
  app:
    build:
      context: .
      target: "composed"
    expose:
      - 8000
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - app
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Americas/Sao_Paulo
    expose:
      - 8191
    depends_on:
      - app
    # ports:
    #   - 8191:8191
    restart: unless-stopped
volumes:
  static_volume:
