version: "3.1"

services:
  app:
    build:
      context: .
      target: "composed"
    expose:
      - 8000
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  static_volume:
