# Generated by Django 4.1.6 on 2023-02-09 23:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('value', models.TextField()),
                ('path', models.CharField(default='/', max_length=256, null=True)),
                ('domain', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector_type', models.CharField(choices=[('css selector', 'Css'), ('xpath', 'Xpath'), ('tag name', 'Tag'), ('class name', 'Class')], max_length=16)),
                ('selector', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('categories', models.ManyToManyField(to='database.category')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128, null=True)),
                ('url', models.CharField(max_length=256)),
                ('custom_selector_type', models.CharField(choices=[('css selector', 'Css'), ('xpath', 'Xpath'), ('tag name', 'Tag'), ('class name', 'Class')], default='css selector', max_length=16, null=True)),
                ('custom_selector', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(choices=[('S', 'Success'), ('O', 'Out of stock'), ('U', 'Undefined status')], default='S', max_length=1, null=True)),
                ('frequency', models.CharField(choices=[('F', 'Four times a day'), ('T', 'Twice a day'), ('D', 'Daily'), ('W', 'Weekly')], default='D', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.product')),
                ('selector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.defaultselector')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.target')),
            ],
        ),
    ]
