# Generated by Django 4.1.6 on 2023-02-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='custom_selector_type',
            field=models.CharField(choices=[('css selector', 'Css'), ('xpath', 'Xpath'), ('tag name', 'Tag'), ('class name', 'Class')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('O', 'Out of stock'), ('N', 'No selector set'), ('P', 'Price not found'), ('U', 'Undefined status')], default='S', max_length=1, null=True),
        ),
    ]
