# Generated by Django 4.1.6 on 2023-02-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_target_custom_selector_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultselector',
            name='name',
            field=models.CharField(default='undefined_name', max_length=64),
            preserve_default=False,
        ),
    ]
