# Generated by Django 4.1.6 on 2023-02-10 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_defaultselector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='cookie',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='defaultselector',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='defaultselector',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
    ]
